default:
    type: "postgres"
    host: "localhost"
    port: 5432
    username: "postgres"
    password: "password"
    database: "rn_meals"
    synchronize: true
    entities:
        - entities/*.ts
    seeds:
        - "database/seeds/**/*.ts"
    factories:
        - "database/factories/**/*.ts"
